### ISSUE TITLE
SSO Setup

### ISSUE THREAD

**Issue by dominikhorn93** [hsa-projects/subject-registration#17]
**Is your feature request related to a problem? Please describe.**
It is not clear if the SSO is setup correctly and how to do that. 

**Describe the solution you'd like**
There should be a prod and a local configuration. The prod configuration uses the ldap, the local one does not. Local contains for it testuser in an own realm.

**Additional context**
- create sso folder in monorepo
- create configuration files
- update example and prod docker-compose yaml

**Comment by dejanreb** [comment]
Should the whole Keycloak app be inside the sso folder or just the config files? And is the config file supposed to be a config for the whole keycloak inside our app or just for the sso topic?

**Comment by dejanreb** [comment]
@dominikhorn93

**Comment by dominikhorn93** [comment]
Keycloak is used with the corresponding docker image. So I would just put the config files into the sso folder. All your specific Keycloak config should be in the sso folder. It is also possible that you different configs for local and production usage.
