### ISSUE TITLE
Investigate alternatives to OpenApi

### ISSUE THREAD

**Issue by hanjul** [hsa-projects/subject-registration#27]
The Frontend currently uses an OpenApi generator to generate bindings to the backend endpoints. This seems unnecessary inflexable. Alternatively, only the `Dto`'s of the backend could be used for typing and `react-query` (or another equivalent) for handling the actual request. Additionally, [orval](https://github.com/anymaniax/orval) could be used to automate this process.

**Comment by dominikhorn93** [comment]
If you want we can also look at GraphQL as a proxy - of course this does not solve the Dto's problem.
