### ISSUE TITLE
Ui/UX: As a professor I want to see all registrations for my course

### ISSUE THREAD

**Issue by dominikhorn93** [hsa-projects/subject-registration#39]
UI:
- Create UX concept for professor
  - Overview of all courses
  - In the course an overview of registrations by registration window

**Comment by dominikhorn93** [comment]
Choose a UI / UX Tool (Figma, Adobe XD ...)

**Comment by marwe97** [comment]
![Bildschirmfoto 2023-01-31 um 17.31.22.png](https://images.zenhubusercontent.com/6256cd28f92995284c9c717c/fd67e206-b7e9-4a38-9cf2-cde7cd93fb79)

**Comment by marwe97** [comment]
![Bildschirmfoto 2023-01-31 um 17.31.53.png](https://images.zenhubusercontent.com/6256cd28f92995284c9c717c/7fbe8282-d100-4b9c-b877-96e0fbe6a99a)

**Comment by marwe97** [comment]
![Bildschirmfoto 2023-01-31 um 17.35.00.png](https://images.zenhubusercontent.com/6256cd28f92995284c9c717c/66f0a771-dfaf-4e5c-ad32-0dbaae987874)

**Comment by marwe97** [comment]
![Bildschirmfoto 2023-01-31 um 17.35.13.png](https://images.zenhubusercontent.com/6256cd28f92995284c9c717c/ef2baeff-da40-44f6-9326-dea9b15ee305)
