### ISSUE TITLE
Send a start registration window email to a set of mail addresses

### ISSUE THREAD

**Issue by dominikhorn93** [hsa-projects/subject-registration#69]
## Description

When the registration window starts, an email is sent to all students.
This is done via service task in camunda.

## Tasks
- define the mail text in code
- define the mail addresses in application.properties
  - inject them via @Value into a property in your mailService
- add mail functionality to the backend (spring mail)
  - mail package with MailService class
  - use a gmail mail adress
- implement a JavaDelegate that calls the MailService
- adjust the bpmn process an the unit test

**Comment by VladKay** [comment]
I implemented the Properties part without "@Value" annotation, because it was the most optimal solution in this case. I need feedback of my code in "mailingBranch", because it was already done
