### ISSUE TITLE
Add Nginx Route to Camunda Cockpit

### ISSUE THREAD

**Issue by dominikhorn93** [hsa-projects/subject-registration#86]
## Description
Camunda should be available via nginx proxy

**Comment by Theta-Dev** [comment]
Der Camunda-Endpoint ist nun erreichbar.

Dass es beim ersten Versuch nicht funktioniert hat lag wahrscheinlich nur an der langen Ladezeit oder so.

https://subject-registration.informatik.hs-augsburg.de/camunda/
