### ISSUE TITLE
As a participant I want to receive mails from the backend application

### ISSUE THREAD

**Issue by dominikhorn93** [hsa-projects/subject-registration#9]
**Is your feature request related to a problem? Please describe.**
No emails are sent from the backend.
The logic is missing / not implemented yet.
Templates texts are available

**Describe the solution you'd like**
Mails are sent to the points in the process.

**Additional context**
- A mail account is requested
- Spring Mail is integrated in the backend
- An element template exists for modeling
- A delegate & mail service exists
- The processes are extended

**Comment by VladKay** [comment]
To achieve the goal, backend should be refactored and project structure has to be restrukted. There are a lot of overhead classes and code pieces that are incorect like: 
` private final UUID id;` **final** without value definition....
`private final RegistrationService registrationService;` **CDI&@Autrowired??**
@dominikhorn93  , Please, give me your feedback :)

**Comment by dominikhorn93** [comment]
Hey Vlad,
`private final UUID id` is totally fine. Initalization is done via constructor that is generated with the Lombok annotation.
Same with CDI. If you take a look at the class you'll find a @RequiredArgsConstruct. With that Lombok generates dependency injection via construct which is much better than using @Autowired. We are using Lombok to avoid boilerplate code.
